# $Id$ 


LOCDIR   = src

include $(ESMF_DIR)/makefile

DIRS        = prologue Infrastructure Superstructure epilogue \
              doc system_tests demos test_harness


CLEANFILES  = 
CLEANDIRS   = 
CLOBBERDIRS = 
DUSTDIRS    = Infrastructure Superstructure system_tests demos test_harness


