# $Id$ 

ALL: build_here

LOCDIR   = src/Superstructure

include $(ESMF_DIR)/makefile

# The ESMF_Mod file is currently in the Component/src directory,
# since this is the last to get built.

DIRS     =  State Component AttributeAPI IOAPI ESMFMod AppDriver

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =










