# $Id$

ALL:  build_examples

run: run_examples

LOCDIR	  = src/Infrastructure/Route/examples

EXAMPLES_BUILD   = 

EXAMPLES_RUN     = 

EXAMPLES_RUN_UNI = 


include ${ESMF_DIR}/makefile

DIRS =


CLEANDIRS   = 
CLEANFILES  = $(EXAMPLES_BUILD)
CLOBBERDIRS =


#
# ESMF_RouteEx
#
run_ESMF_RouteEx:

run_ESMF_RouteEx_uni:


