# $Id: makefile,v 1.9 2006/09/22 23:55:47 theurich Exp $ 

ALL: tree_build_system_tests

run: tree_run_system_tests

CFLAGS    = 
FFLAGS    =
SOURCEC	  = 
SOURCEF	  =

SOURCEH	  = 
OBJSC	  =  
OBJSF	  = 
MANSEC	  = 
LIBBASE	  = 
LOCDIR	  = src/system_tests/ESMF_AttributeStress


SYSTEM_TESTS_BUILD    = $(ESMC_TESTDIR)/ESMF_AttributeStress


ESMF_AttributeStress.o :

include $(ESMF_DIR)/makefile

DIRS = 

CLEANDIRS   =
CLEANFILES  = $(SYSTEM_TESTS_BUILD)
CLOBBERDIRS =



