# $Id$

all: demos

LOCDIR   = src/demos

include $(ESMF_DIR)/makefile

DIRS     = 
# Disabled while putting new fields into grids.
# coupled_flow 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =


# DO NOT DELETE
