#!/bin/bash
#
#PBS -N #testname#
#PBS -A P93300606
#PBS -l walltime=04:00:00
#PBS -q economy
#PBS -l select=1:ncpus=16:mpiprocs=16
#PBS -j oe
#PBS -m ae
#PBS -o #testname#.out
#PBS -e #testname#.err



#homedir#
#logdir#

#modules#

#clearesmfvars#

#esmfdir#

# commonesmfvars before esmfenv to overwrite ESMF_MPIRUN for mpiuni cases
#commonesmfvars#
#esmfenv#
#esmfbopt#

#demodir#

bash $homedir/test_esmf_local > test_esmf_local.out

exit 0
