#!/bin/bash
#
#PBS -N intel18impi
#PBS -A P93300606
#PBS -l walltime=04:00:00
#PBS -q economy
#PBS -l select=1:ncpus=16:mpiprocs=16
#PBS -j oe
#PBS -m ae
#PBS -o intel18impi.out
#PBS -e intel18impi.err



export homedir=/glade/work/rokuingh/sandbox/test_scripts/manual_testing
export LOGDIR=/glade/work/rokuingh/sandbox/esmpyintel18test/logs

module purge; module use /glade/work/rokuingh/python/3.6.8/intel/18.0.5/modules; module load ncarenv/1.3 intel/18.0.5 ncarcompilers/0.5.0 impi/2018.4.274 netcdf/4.7.1 python/3.6.8intel;

unset ESMF_OS; unset ESMF_ABI; unset ESMF_SITE; unset ESMF_TESTEXHAUSTIVE; unset ESMF_TESTWITHTHREADS; unset ESMF_MPIRUN; unset ESMF_COMPILER; unset ESMF_COMM; unset ESMF_NETCDF; unset ESMF_NETCDF_INCLUDE; unset ESMF_NETCDF_LIBPATH; unset ESMF_PNETCDF; unset ESMF_PNETCDF_INCLUDE; unset ESMF_PNETCDF_LIBPATH; unset ESMF_PROJ4; unset ESMF_PROJ4_INCLUDE; unset ESMF_PROJ4_LIBPATH; unset ESMF_YAMLCPP; unset ESMF_CXXCOMPILEOPTS; unset ESMF_F90COMPILEOPTS; unset ESMF_NUM_PROCS; unset ESMF_OPTLEVEL; unset ESMF_MPIMPMDRUN;

export ESMF_DIR=/glade/work/rokuingh/sandbox/esmpyintel18test/esmf

# commonesmfvars before esmfenv to overwrite ESMF_MPIRUN for mpiuni cases
export ESMF_OS=Linux; export ESMF_ABI=64; export ESMF_SITE=default; export ESMF_TESTEXHAUSTIVE=ON; export ESMF_TESTWITHTHREADS=OFF; export ESMF_MPIRUN=mpirun;
export ESMF_COMPILER=intel; export ESMF_COMM=intelmpi; export ESMF_NETCDF=split; export ESMF_NETCDF_INCLUDE=/glade/u/apps/ch/opt/netcdf/4.7.1/intel/18.0.5/include; export ESMF_NETCDF_LIBPATH=/glade/u/apps/ch/opt/netcdf/4.7.1/intel/18.0.5/lib; export ESMF_NUM_PROCS=4;
export ESMF_BOPT=O

bash $homedir/test_esmpy_local > test_esmpy_local.out

exit 0
