#!/bin/bash
#
#PBS -N CheyenneMPTMeshCreate%np%
#PBS -A P93300606
#PBS -l walltime=00:30:00
#PBS -q economy
#PBS -l select=%nn%:ncpus=36:mpiprocs=36
#PBS -j oe
#PBS -m ae
#PBS -o CheyenneMPTMeshCreate%np%.out
#PBS -e CheyenneMPTMeshCreate%np%.err

mpiexec_mpt ./CheyenneMPTMeshCreate %grid1% %grid2%

