# $Id$ 

ALL: build_here

LOCDIR   = src/Infrastructure

include $(ESMF_DIR)/makefile


DIRS     = 	stubs Util Base IOSpec LogErr IO TimeMgr VM DELayout \
		Config ArraySpec LocalArray Route DistGrid Array ArrayBundle \
		Grid Mesh GridUtil LocStream GeomBase Regrid Field FieldComm \
                FieldBundle Attribute 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



